services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${GLUETUN_TZ}
      - LOG_LEVEL=${GLUETUN_LOG_LEVEL}
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=${GLUETUN_UPDATER_PERIOD}
    ports:
      - "8888:8888/tcp" # HTTP proxy
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped

  curl-container:
    image: curlimages/curl
    container_name: curl-container
    network_mode: "service:gluetun"
    command: sh -c "while true; do curl -s ifconfig.me; echo; sleep 10; done"
    depends_on:
      - gluetun
    restart: unless-stopped
